from applications.reports.models.monthly import MonthlyReport
from applications.reports.models.abstract_report import AbstractReport
from applications.reports.models.distance_max_average import DistanceMaxAverageReport
from applications.reports.models.use_of_vehicle import AbstractUseOfVehicleReport
from applications.reports.models.use_of_vehicle import RealUseOfVehicleReport
from applications.reports.models.use_of_vehicle import TheoreticalUseOfVehicleReport
from applications.reports.models.punctuality import PunctualityReport
from applications.reports.models.use_without_reservation import UseWithoutReservation
