from applications.maintenance.views.cleaning.card import CleaningCardViewSet
from applications.maintenance.views.cleaning.cleaning import CleaningViewSet
from applications.maintenance.views.cleaning.photo import CleaningPhotoViewSet
from applications.maintenance.views.itv.itv import ItvViewSet
from applications.maintenance.views.itv.photo import ItvPhotoViewSet
from applications.maintenance.views.odometer.odometer import OdometerViewSet
from applications.maintenance.views.odometer.photo import OdometerPhotoViewSet
from applications.maintenance.views.revision.photo import RevisionPhotoViewSet
from applications.maintenance.views.revision.revision import RevisionViewSet
from applications.maintenance.views.wheels.photo import WheelsPhotoViewSet
from applications.maintenance.views.wheels.wheels import WheelsViewSet
