# Generated by Django 4.0.5 on 2022-09-23 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_tenant_diet'),
        ('reservations', '0002_reservation_incidents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('modified', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_stored', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to='reservations.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'Diet',
            },
        ),
        migrations.CreateModel(
            name='DietPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Parking', 'Parking'), ('Peaje', 'Peaje'), ('Alojamiento', 'Alojamiento'), ('Otros', 'Otros')], default='Otros', max_length=20)),
                ('liters', models.IntegerField(blank=True, default=-1)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='diets.diet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'DietPayment',
            },
        ),
        migrations.CreateModel(
            name='DietPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='diet/none.png', upload_to='diets')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_photos', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='diets.dietpayment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'DietPhoto',
            },
        ),
    ]
