# Generated by Django 4.0.5 on 2022-09-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='number_of_diets',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
