# Generated by Django 4.0.5 on 2022-09-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietcollection',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
