# Generated by Django 4.0.5 on 2022-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='number_of_diets',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
