# Generated by Django 4.0.5 on 2022-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_alter_diet_number_of_diets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dietpayment',
            name='liters',
            field=models.DecimalField(blank=True, decimal_places=2, default=-1, max_digits=6),
        ),
    ]
