# Generated by Django 4.1.2 on 2022-10-14 16:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_short_name'),
        ('diets', '0003_alter_dietpayment_amount_alter_dietpayment_liters'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietMonthlyPdfReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pdf', models.FilePathField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'DietMonthlyPdfReport',
            },
        ),
    ]
