# Generated by Django 4.0.4 on 2022-06-23 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_vehicle_icon'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pdf', models.FilePathField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'MonthlyReport',
            },
        ),
        migrations.CreateModel(
            name='UseWithoutReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=5, max_digits=10)),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.monthlyreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_without_reservation_reports', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'UseWithoutReservation',
            },
        ),
        migrations.CreateModel(
            name='TheoreticalUseOfVehicleReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=5, max_digits=10)),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.monthlyreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theoretical_use_of_vehicle_reports', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'TheoreticalUseOfVehicleReport',
            },
        ),
        migrations.CreateModel(
            name='RealUseOfVehicleReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=5, max_digits=10)),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.monthlyreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_use_of_vehicle_reports', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'RealUseOfVehicleReport',
            },
        ),
        migrations.CreateModel(
            name='PunctualityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('take_out', models.DecimalField(decimal_places=5, max_digits=10)),
                ('take_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('free_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('free_out', models.DecimalField(decimal_places=5, max_digits=10)),
                ('not_taken', models.DecimalField(decimal_places=5, max_digits=10)),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.monthlyreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuality_reports', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'PunctualityReport',
            },
        ),
        migrations.CreateModel(
            name='DistanceMaxAverageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('distance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('max_speed', models.DecimalField(decimal_places=5, max_digits=10)),
                ('average_speed', models.DecimalField(decimal_places=5, max_digits=10)),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.monthlyreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_max_average_reports', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'DistanceMaxAverageReport',
            },
        ),
    ]
