# Generated by Django 4.1.7 on 2023-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traccar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
