# Generated by Django 4.0.3 on 2022-04-12 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_stored', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tenant',
            },
        ),
    ]
