# Generated by Django 4.0.5 on 2022-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
