# Generated by Django 4.0.3 on 2022-04-12 10:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('fullname', models.CharField(max_length=70, verbose_name='fullname')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=11)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='RecoverPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_stored', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=9)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recover_passwords', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recover_passwords', to='tenants.tenant')),
            ],
            options={
                'db_table': 'Recover Password',
                'ordering': ['-date_stored'],
            },
        ),
    ]
