# Generated by Django 4.0.3 on 2022-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_vehicles',
            field=models.ManyToManyField(related_name='allowed_vehicles', through='allowed_vehicles.AllowedVehicles', to='vehicles.vehicle'),
        ),
    ]
