# Generated by Django 4.0.4 on 2022-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allowed_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ble_user_id',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
