# Generated by Django 4.1.2 on 2022-11-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantbillingmonthlypdfreport'),
        ('users', '0004_user_is_interventor_user_is_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('DELETED', 'Deleted')], default='CREATED', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_history', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserRegistrationHistory',
                'ordering': ['-date'],
            },
        ),
    ]
