# Generated by Django 4.1.2 on 2022-11-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenantbillingmonthlypdfreport_date_stored'),
        ('users', '0006_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationhistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_registration_history', to='tenants.tenant'),
        ),
    ]
