PDF_W = 210
PDF_H = 297

DEFAULT_FONT_FAMILY = 'DejaVu'

HORIZONTAL_LEFT_MARGIN = 20
HORIZONTAL_RIGHT_MARGIN = HORIZONTAL_LEFT_MARGIN
HEADER_TOP_MARGIN = 8
WRITABLE_WIDTH = PDF_W - HORIZONTAL_LEFT_MARGIN - HORIZONTAL_RIGHT_MARGIN
