# Generated by Django 4.1.2 on 2023-02-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WheelsCard',
        ),
    ]
