# Generated by Django 4.1.2 on 2023-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_delete_wheelscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheels',
            name='next_kilometers',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wheels',
            name='next_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
