# Generated by Django 4.1.2 on 2023-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_wheels_next_kilometers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=14),
        ),
    ]
