# Generated by Django 4.1.7 on 2023-02-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_cleaning_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='odometer',
            name='old_kilometers',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
