# Generated by Django 4.1.7 on 2023-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_repairment_odometer_status_repairmentphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='cause_status',
            field=models.CharField(choices=[('KILOMETERS', 'KILOMETERS'), ('DATE', 'DATE')], default='KILOMETERS', max_length=14),
        ),
        migrations.AddField(
            model_name='wheels',
            name='cause_status',
            field=models.CharField(choices=[('KILOMETERS', 'KILOMETERS'), ('DATE', 'DATE')], default='KILOMETERS', max_length=14),
        ),
    ]
