# Generated by Django 4.0.4 on 2022-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='icon',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
