# Generated by Django 4.0.4 on 2022-06-27 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
