# Generated by Django 4.0.5 on 2022-09-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_number_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('TOURISM', 'TOURISM'), ('ALL_TERRAIN', 'ALL_TERRAIN'), ('MOTORCYCLE', 'MOTORCYCLE'), ('VAN', 'VAN'), ('TRUCK', 'TRUCK')], default='TOURISM', max_length=20),
        ),
    ]
