# Generated by Django 4.1.2 on 2022-11-11 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenantbillingmonthlypdfreport_date_stored'),
        ('vehicles', '0005_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_stored',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='VehicleRegistrationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('DELETED', 'Deleted')], default='CREATED', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_registration_history', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_history', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'VehicleRegistrationHistory',
                'ordering': ['-date'],
            },
        ),
    ]
