# Generated by Django 4.1.2 on 2022-11-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_date_stored_vehicleregistrationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
