# Generated by Django 4.1.7 on 2023-05-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='icon',
        ),
    ]
