# Generated by Django 4.1.7 on 2023-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_remove_vehicle_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/icons'),
        ),
    ]
