# Generated by Django 4.0.3 on 2022-04-12 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_stored', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(default='incidents/none.png', upload_to='incidents')),
                ('type', models.CharField(choices=[('TIRE_PUNCTURE', 'Pinchazo'), ('BANG', 'Golpe'), ('USAGE_PROBLEMS', 'Problemas de uso'), ('LIGHTS', 'Luces'), ('OTHERS', 'Otros')], default='OTHERS', max_length=14)),
                ('solved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
                ('solver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_incidents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'Incident',
                'ordering': ['-date_stored'],
            },
        ),
    ]
