# Generated by Django 4.0.5 on 2022-09-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_self_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='solver_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
