# Generated by Django 4.0.3 on 2022-04-12 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('reservations', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='incidents',
            field=models.ManyToManyField(related_name='incidents', through='incidents.Incident', to=settings.AUTH_USER_MODEL),
        ),
    ]
