# Generated by Django 4.1.2 on 2022-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_recurrent_date_stored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_stored',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
