name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: test-key-not-good
      SMTP_PORT: 465
      SMTP_SERVER: smtp.gmail.com

      EMAILS_STATUS: disabled
      SENDER_EMAIL: testing@gmail.com
      SENDER_PASSWORD: password

      TRACCAR_URL: http://localhost
      TRACCAR_PORT: 8082
      TRACCAR_USER: admin
      TRACCAR_PASSWORD: admin

      SERVER_URL: 'https://fleetmanagement.com'
      
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Run Tests
      env:
          DEBUG: "0"
          SECRET_KEY: ${{ env.SECRET_KEY }}
      run: |
        python src/manage.py test
